web/router.ex
defmodule Ombib.Router do
  use Ombib.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Ombib.CurrentUser
  end

  pipeline :login_required do
    plug Guardian.Plug.EnsureAuthenticated, handler: Ombib.GuardianErrorHandler
  end

  pipeline :admin_required do
    plug Ombib.CheckAdmin
  end

  # guest zone
  scope "/", Ombib do
    pipe_through [:browser, :with_session]

    get "/", PageController, :index
	
    resources "/users", UserController, only: [:show, :new, :create]
	
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    # registered user zone
    scope "/" do
      pipe_through [:login_required]

      resources "/users", UserController, only: [:show] do
        resources "/posts", PostController
      end

      # admin zone
      scope "/admin", Admin, as: :admin do
        pipe_through [:admin_required]

        resources "/users", UserController, only: [:index, :show] do
          resources "/posts", PostController, only: [:index, :show]
        end

      end

    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", Ombib do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Ombib.LayoutView do
  use Ombib.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Ombib!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <ol class="breadcrumb text-right">
          <%= if @current_user do %>
            <li><%= @current_user.email%></li>
            <li>
                <%= link "My posts", to: user_post_path(@conn, :index, @current_user) %>
            </li>
            <%= if @current_user.is_admin do %>
              <li>
                <%= link "Users", to: admin_user_path(@conn, :index) %>
              </li>
            <% end %>
            <li>
                <%= link "Sign out", to: session_path(@conn, :delete, @current_user), method: "delete" %>
            </li>
          <% else %>
            <li><%= link "Register", to: user_path(@conn, :new) %></li>
            <li><%= link "Sign in", to: session_path(@conn, :new) %></li>
          <% end %>
        </ol>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>